#!/bin/bash -
#===============================================================================
#
#          FILE: .envrc.sh
#
#         USAGE: ./.envrc.sh
#
#   DESCRIPTION:
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: Evan Mattiza (),
#  ORGANIZATION:
#       CREATED: 06/07/2021 08:19:00 PM
#      REVISION:  ---
#===============================================================================

dtf () {
  dhall-to-json <<< ./$1 > ${1%.dhall}.tf.json
  terraform init
  terraform validate
}
