name: "Build"
on:
  pull_request:
  push:
    branches:
    - master
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-22.04, macos-13]
    steps:
    - uses: actions/checkout@v3.6.0

    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: nix store cache
      uses: actions/cache@v3
      with:
        path: /nix/store
        key: ${{ runner.os }}--nix-store

    - run: nix build

    - run: nix run . -- --help 

    - uses: actions/upload-artifact@v4
      with:
        name: dhall-terraform-${{matrix.os}}
        path: result/bin/dhall-terraform-libgen