name: "Build"
on:
  pull_request:
  push:
    branches:
    - '*'
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os:
              - ubuntu-22.04 # linux-amd64
              # - ubuntu-22.04-arm # linux-arm64
              # - macos-13 # darwin-amd64
              # - macos-14 # darwin-arm64
    steps:
    - uses: actions/checkout@v3.6.0

    - uses: cachix/install-nix-action@v22
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - if: matrix.os == 'ubuntu-22.04'
      run: sudo apt-get remove -y libc6-dev

    - if: matrix.os == 'ubuntu-22.04-arm'
      run: sudo apt-get remove -y libc6-dev

    - run: make setup

    - run: make build

    - run: make test

    # - if: ${{ matrix.os == 'ubuntu-22.04' }}
    #   run: OS=linux ARCH=amd64 ./utils/prep-release.sh

    # - if: ${{ matrix.os == 'macos-13' }}
    #   run: OS=darwin ARCH=amd64 ./utils/prep-release.sh

    - uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'ubuntu-22.04' }}
      with:
        name: dhall-terraform-linux-amd64
        path: dist/dhall-terraform-libgen

    - uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'ubuntu-22.04-arm' }}
      with:
        name: dhall-terraform-linux-arm64
        path: dist/dhall-terraform-libgen

    - uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'macos-13' }}
      with:
        name: dhall-terraform-darwin-amd64
        path: dist/dhall-terraform-libgen

    - uses: actions/upload-artifact@v4
      if: ${{ matrix.os == 'macos-14' }}
      with:
        name: dhall-terraform-darwin-arm64
        path: dist/dhall-terraform-libgen
